# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    container_name: db
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: andreyspb/kittygram_backend
    container_name: backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
  frontend:
    image: andreyspb/kittygram_frontend  # Качаем с DockerHub
    container_name: frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: andreyspb/kittygram_gateway  # Качаем с DockerHub
    container_name: gateway
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/media
    ports:
      - 8080:80
