# docker-compose.production.yml
version: '3'

volumes:
  pg_data_production:
  static:
  media:

# Всё отличие – заменяем build на image и указываем, какой образ использовать
services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: andreyspb/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  frontend:
    image: andreyspb/kittygram_frontend  # Качаем с DockerHub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: andreyspb/kittygram_gateway  # Качаем с DockerHub
    env_file: .env
    volumes:
      - static:/staticfiles/
      - media:/media
    ports:
      - 8080:80
    depends_on:
      - backend
